apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
  namespace: test-php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: code
        emptyDir: {}
      containers:
      - name: php
        image: php:7-fpm
        volumeMounts:
        - name: code
          mountPath: /code
      initContainers:
      - name: install
        image: alpine/git
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              git clone https://github.com/Veroncheg/test-php-app.git &&
              cd test-php-app/php-app &&
              cp -R . /code/